services:
  dcaspt2:
    container_name: 'dirac_build_bullseye'
    hostname: 'dirac_build_bullseye'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    # Login as non-root user (docker)
    # because mpirun does not work as root
    # except if --allow-run-as-root option is used
    environment:
      GID: 1000
      UID: 1000
      USER: docker
    user: docker
    working_dir: /workspace/dirac
